### ISSUE TITLE
Bug: Broken links in hkdc dataset

### ISSUE THREAD

**Issue by martinctc** [Hong-Kong-Districts-Info/hkdatasets#9]
From the `hkdc` dataset, the following are the constituency code with invalid Facebook links: 
- `A-09`
- `C-24`
- `D-10`
- `G-13`
- `G-17`
- `H-08`
- `H-11`
- `H-16`
- `J-19`
- `J-21`
- `J-33`
- `L-22` 
- `L-26` 
- `N-04` 
- `P-11`
- `R-15`
- `S-09`

**Comment by elgarteo** [comment]
I've looked up the correct Facebook links for the constituencies above as well as those marked as "N/A" in the dataset.
[missing_fb_links.xlsx](https://github.com/Hong-Kong-Districts-Info/hkdatasets/files/5479650/missing_fb_links.xlsx)

**Comment by martinctc** [comment]
Have merged in the updated links you've provided in PR #8. Thanks @elgarteo!
